### ISSUE TITLE
Device not found 

### ISSUE THREAD

**Issue by arnelcabinti** [fiorix/nitgen-bsp#6]
I got this error then when I ran python search_engine.py on my terminal.
I also plug-in my device. Can you help me to resolve this issue.Thanks for the response.
 
Traceback (most recent call last):
  File "search_engine.py", line 12, in <module>
    nbio = NitgenBSP.Handler()
  File "/usr/local/lib/python2.7/dist-packages/NitgenBSP/__init__.py", line 75, in __init__
    self._handler, self.__image_width, self.__image_height = _bsp_core.open()
RuntimeError: device not found

**Comment by fiorix** [comment]
You could check on `dmesg` to look for messages related to USB devices. This error states that the Nitgen library cannot find your device, which leads me to believe your system might be missing a USB kernel module or something along those lines. Perhaps `lsusb` could help too.

Unfortunately I don't have any Nitgen devices to reproduce this.
